import axios from "axios";
import { Content } from "components/content/content";
import { server } from "config";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";

export default function Chapter({ data }) {
  const { chapter_endpoint, chapter_image, chapter_name, chapter_page, title } =
    data;
  // console.log("ini post", data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Home</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_RAPIDAPI_KEY}</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_HOST}</h1> */}
      {/* <Content /> */}
      <div className="container lg:px-24">
        <div className="flex flex-col space-y-4">
          <h1>{title}</h1>
          <div className="flex flex-col space-y-6">
            <h1>{chapter_name}</h1>
            <div className="img">
              <div className="relative w-full h-full">
                {chapter_image?.map((d, i) => (
                  <Image
                    key={i}
                    src={d.chapter_image_link}
                    alt={chapter_name}
                    layout="fill"
                    objectFit="cover"
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  // Call an external API endpoint to get posts
  const { id } = context.query;
  const res = await fetch(`${server}/api/chapter/${id}`);
  const data = await res.json();

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
    },
  };
}
