import axios from "axios";
import { Content } from "components/content/content";
import { server } from "config";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

// import styles from "../styles/Home.module.css";
export default function Chapter() {
  const router = useRouter();
  const { id } = router.query;
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const { chapter_endpoint, chapter_image, chapter_name, chapter_page, title } =
    data;

  const getData = async () => {
    try {
      setLoading(true);
      const { data } = await AxiosAPP(`/api/chapter/${id}`);
      setData(data);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Home</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_RAPIDAPI_KEY}</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_HOST}</h1> */}
      {/* <Content /> */}
      <div className="container lg:px-24">
        <div className="flex flex-col space-y-4">
          <h1>{title}</h1>
          <div className="flex flex-col space-y-6">
            <h1>{chapter_name}</h1>
            <div className="img">
              <div className="relative w-full h-full">
                {chapter_image?.map((d, i) => (
                  <Image
                    key={i}
                    src={d.chapter_image_link}
                    alt={chapter_name}
                    layout="fill"
                    objectFit="cover"
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// export async function getServerSideProps(context) {
//   // Call an external API endpoint to get posts
//   const { id } = context.query;
//   const res = await fetch(`${server}/api/chapter/${id}`);
//   const data = await res.json();

//   // By returning { props: { posts } }, the Blog component
//   // will receive `posts` as a prop at build time
//   return {
//     props: {
//       data,
//     },
//   };
// }
