import axios from "axios";
// import { Content } from "components/content/content";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Chapter() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="google-site-verification"
          content="aX_-Lu_g7LPtYAvpUMQBSTeRhszIhVwmIojpAxsnhsI"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="img flex flex-col max-w-lg items-center relative">
        <h1>Chapter</h1>
      </div>
    </div>
  );
}
