import axios from "axios";
import { Content } from "components/content/content";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";
// axios;
export default function Chapter({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Home</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_RAPIDAPI_KEY}</h1> */}
      {/* <h1>{process.env.NEXT_PUBLIC_HOST}</h1> */}
      {/* <Content /> */}
      <div className="img flex flex-col max-w-lg items-center relative">
        {/* {chapter_image.map((data, i) => (
          <Image
            key={i}
            src={data.chapter_image_link}
            layout="fill"
            objectFit="contain"
            alt={title}
          />
        ))} */}
        <h1>Chapter</h1>
      </div>
    </div>
  );
}

