import axios from "axios";
// import { Content } from "components/content/content";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";
// axios;
export default function Chapter() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="img flex flex-col max-w-lg items-center relative">
        <h1>Chapter</h1>
      </div>
    </div>
  );
}
